"""
Created on Fri Mar  7 16:58:55 2014

@author: zoherghadyali, jaywoo, sophiali
"""

world1 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W              W                  W",
        "W              W                  W",
        "W   WWWW       W                  W",
        "W   W          WWWW               W",
        "W   W                             W",
        "W   W                             W",
        "W   W                   WWWWWWWWWWW",
        "W   WWWWWWW             W         W",
        "W         W             W         W",
        "W         WWWW          W         W",
        "W                                 W",
        "W WWWWWWWWWWWW                    W",
        "W                                 W",
        "W                                 W",
        "W                                 W",
        "W                                 W",
        "W                                 W",
        "W                                 W",
        "W                                 W",
        "W               WWWWWWWWWWWW      W",
        "W               W                 W",
        "W               W                 W",
        "WW              W  C              W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        ]

world2 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                 W",
        "W         WWWWWW                  W",
        "W   WWWW       W                  W",
        "W                                 W",
        "W                                 W",
        "W                                 W",
        "W                                WW",
        "W   WWW WWW   W W                 W",
        "W     W   W   W W                 W",
        "WWW   W   WWWWW W                 W",
        "W W      WW                       W",
        "W W   WWWW   WWW                  W",
        "W     W    W   W                  W",
        "W                                 W",
        "W                                 W",
        "W                                 W",
        "W                                 W",
        "W                                 W",
        "W                                 W",
        "W               WWWWWWWWWWWWWWWWW W",
        "W                                 W",
        "W                                 W",
        "WW                                W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",]